version: 1
default_environment: dev
project_id: 0559b800-5b81-444f-9f54-a2f515b843e1
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    config:
      files:
       -  entity: product_category_name_translation
          path: ./raw/product_category_name_translation.csv
          keys: [product_category_name]
          encoding: utf-8
       - entity: olist_customers_dataset
         path: ./raw/olist_customers_dataset.csv
         keys: [customer_id]
         encoding: utf-8
       - entity: olist_geolocation_dataset
         path: ./raw/olist_geolocation_dataset.csv
         keys: [geolocation_zip_code_prefix]
         encoding: utf-8
       - entity: olist_orders_dataset
         path: ./raw/olist_orders_dataset.csv
         keys: [order_id]
         encoding: utf-8
       - entity: olist_order_items_dataset
         path: ./raw/olist_order_items_dataset.csv
         keys: [order_id, order_item_id]
         encoding: utf-8
       - entity: olist_order_payments_dataset
         path: ./raw/olist_order_payments_dataset.csv
         keys: [order_id, payment_sequential]
         encoding: utf-8
       - entity: olist_order_reviews_dataset
         path: ./raw/olist_order_reviews_dataset.csv
         keys: [review_id]
         encoding: utf-8
       - entity: olist_products_dataset
         path: ./raw/olist_products_dataset.csv
         keys: [product_id]
         encoding: utf-8
       - entity: olist_sellers_dataset
         path: ./raw/olist_sellers_dataset.csv
         keys: [seller_id]
         encoding: utf-8
      delimiter: ','
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git
    config:
      batch_size: 104857600
      project: sonic-verbena-461903-e8
      dataset: olist_dataset
      credentials_path: /home/fabe/project2/.keys/json_key_olist.json
      method: batch_job
      denormalized: true
      flattening_enabled: true
      flattening_max_depth: 1
